### ISSUE TITLE
Error withKong startup the eficode/wait-for ADD fails

### ISSUE THREAD

**Issue by jgdasilva** [babbtx/pingoneauthorize-api-tutorials#2]
=> ERROR [kong] https://raw.githubusercontent.com/eficode/wait-for/v2.2.1/wait-for

 > [kong] https://raw.githubusercontent.com/eficode/wait-for/v2.2.1/wait-for:
------
failed to solve: failed to load cache key: invalid not-modified ETag: "2dca0c65b70c2f9510fcd1a61714d32ddf765368476952703c997943b2af90b1"

I fixed it by changing the entry in Dockerfile-kong to use v2.2.2 instead of 2.2.1

**Comment by kenneth-ping** [comment]
Hey John thanks for taking the time to write this out and I'm glad you were able to work around it.  Googling this error it seems that it is more likely a result of [caused by your version of Docker](https://github.com/moby/buildkit/issues/2832).  I couldn't repro this in my env:

Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d28e
 Built:             Thu Jul 29 13:55:47 2021
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.22.0 (117440)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

I wanted to check with you to see if you had any more information.  Thanks

**Comment by jgdasilva** [comment]
When I ran into this I think I was on Mac docker desktop 4.22.1, which had docker engine 24.0.5, try to keep with the latest docker builds as I use it a lot.

I just upgraded to the latest which is 4.23.0 with engine 24.0.6

I will clone the project again and try it and see if the error persists.

**Comment by jgdasilva** [comment]
Upgrading docker has fixed it.

**Comment by kenneth-ping** [comment]
Excellent, thanks!
